"""initial migration

Revision ID: 465c9357681f
Revises: 
Create Date: 2026-10-06 01:39:12.926241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465c9357681f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_controllers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('firmeware_version', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_controllers_id'), 'tb_controllers', ['id'], unique=False)
    op.create_index(op.f('ix_tb_controllers_serial_number'), 'tb_controllers', ['serial_number'], unique=True)
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_users_email'), 'tb_users', ['email'], unique=True)
    op.create_index(op.f('ix_tb_users_id'), 'tb_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_users_id'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_email'), table_name='tb_users')
    op.drop_table('tb_users')
    op.drop_index(op.f('ix_tb_controllers_serial_number'), table_name='tb_controllers')
    op.drop_index(op.f('ix_tb_controllers_id'), table_name='tb_controllers')
    op.drop_table('tb_controllers')
    # ### end Alembic commands ###
