"""initial database

Revision ID: 5682cf3a9328
Revises: 
Create Date: 2026-10-07 18:33:35.498032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5682cf3a9328'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_controllers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('firmeware_version', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_controllers_id'), 'tb_controllers', ['id'], unique=False)
    op.create_index(op.f('ix_tb_controllers_serial_number'), 'tb_controllers', ['serial_number'], unique=True)
    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('Created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_users_email'), 'tb_users', ['email'], unique=True)
    op.create_index(op.f('ix_tb_users_id'), 'tb_users', ['id'], unique=False)
    op.create_table('tb_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), server_default='unknown', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['tb_controllers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('controller_id', 'channel', name='uq_device_controller_channel')
    )
    op.create_index(op.f('ix_tb_device_controller_id'), 'tb_device', ['controller_id'], unique=False)
    op.create_index(op.f('ix_tb_device_id'), 'tb_device', ['id'], unique=False)
    op.create_table('tb_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.Column('response', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['tb_device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tb_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_commands_device_id'), 'tb_commands', ['device_id'], unique=False)
    op.create_index(op.f('ix_tb_commands_id'), 'tb_commands', ['id'], unique=False)
    op.create_index(op.f('ix_tb_commands_status'), 'tb_commands', ['status'], unique=False)
    op.create_index(op.f('ix_tb_commands_user_id'), 'tb_commands', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_commands_user_id'), table_name='tb_commands')
    op.drop_index(op.f('ix_tb_commands_status'), table_name='tb_commands')
    op.drop_index(op.f('ix_tb_commands_id'), table_name='tb_commands')
    op.drop_index(op.f('ix_tb_commands_device_id'), table_name='tb_commands')
    op.drop_table('tb_commands')
    op.drop_index(op.f('ix_tb_device_id'), table_name='tb_device')
    op.drop_index(op.f('ix_tb_device_controller_id'), table_name='tb_device')
    op.drop_table('tb_device')
    op.drop_index(op.f('ix_tb_users_id'), table_name='tb_users')
    op.drop_index(op.f('ix_tb_users_email'), table_name='tb_users')
    op.drop_table('tb_users')
    op.drop_index(op.f('ix_tb_controllers_serial_number'), table_name='tb_controllers')
    op.drop_index(op.f('ix_tb_controllers_id'), table_name='tb_controllers')
    op.drop_table('tb_controllers')
    # ### end Alembic commands ###
